// Generated by Copilot with project conventions
/**
 * Subscription service with React Query
 */
import { createReactQueryService } from './reactQueryService';

export interface Subscription {
  id: number;
  championship_id: number;
  team_id: number;
}

export const subscriptionService = createReactQueryService<Subscription>({
  entityName: 'Inscrição',
  endpoint: '/subscription',
});

export const {
  useGetAll: useGetAllSubscriptions,
  useGetById: useGetSubscriptionById,
  useCreate: useCreateSubscription,
  useUpdate: useUpdateSubscription,
  useDelete: useDeleteSubscription,
} = subscriptionService;
